FROM lukin0110/debian-armhf-nodejs-base
MAINTAINER Maarten Huijsmans <maarten@lukin.be>

RUN curl -sL https://deb.nodesource.com/setup_0.12 | sudo -E bash -
RUN apt-get install -y nodejs

WORKDIR /app
